### ISSUE TITLE
beware: null is falsy object 

### ISSUE THREAD

**Issue by dvv** [cloudhead/eyes.js#2]
Hi!

Please, consider injecting in then middle of condition at https://github.com/cloudhead/eyes.js/blob/master/lib/eyes.js#L151 the following

`&& o !== null`

to cope with JS bug which is `typeof null === 'object'`.

TIA,
--Vladimir

**Comment by laurie71** [comment]
I'm guessing this would fix the issue I was about to post:

```
$ node -e "require('eyes').inspector()([null])"

/Users/laurie/.node_libraries/.npm/eyes/0.1.6/package/lib/eyes.js:151
    return (typeof(o) === 'object' && Object.keys(o).length > 0) || 
                                             ^       
TypeError: Object.keys called on non-object
    at Function.keys (native)
    at /Users/laurie/.node_libraries/.npm/eyes/0.1.6/package/lib/eyes.js:151:50
    at Array.some (native)
    at stringifyArray (/Users/laurie/.node_libraries/.npm/eyes/0.1.6/package/lib/eyes.js:150:59)
    at /Users/laurie/.node_libraries/.npm/eyes/0.1.6/package/lib/eyes.js:127:38
    at stringify (/Users/laurie/.node_libraries/.npm/eyes/0.1.6/package/lib/eyes.js:130:6)
    at Object.inspect (/Users/laurie/.node_libraries/.npm/eyes/0.1.6/package/lib/eyes.js:50:27)
    at /Users/laurie/.node_libraries/.npm/eyes/0.1.6/package/lib/eyes.js:39:29
    at Object.<anonymous> (eval at <anonymous> (eval:1:82))
    at Object.<anonymous> (eval:1:70)
```

**Comment by dvv** [comment]
Exactly

**Comment by mildsunrise** [comment]
Since #5 has been merged, this should be closed.
